baseURL: "https://www.covid19dataportal.se/"
title: "COVID-19 Data Portal Sweden"
params:
  title: "COVID-19 Data Portal Sweden"
  description: COVID-19 Data Portal for Swedish Research
  images:
    - /img/site_logo/CV19DP_logo_oneliner_SWE.png

  # There is a hugo i18n package, but it seems like overkill for so few strings
  lang_strings:
    en:
      home_title: Accelerating research through data sharing
      enquire_email_footer_dc: "Contact the Swedish COVID-19 Data Portal"
      enquire_email_footer_bioinformatics: "For bioinformatics support, please contact"
      support_feedback: Support & Feedback
      privacy: Privacy Notice
      skip_to_content: Skip to main content
    sv:
      home_title: Snabbare forskning genom datadelning
      enquire_email_footer_dc: "Kontakta den svenska Covid-19 dataportalen"
      enquire_email_footer_bioinformatics: "För support inom bioinformatik, kontakta"
      support_feedback: Support och Feedback
      privacy: Integritetspolicy
      skip_to_content: Hoppa till innehållet

languages:
  en:
    languageName: English
    contentDir: content/english
    weight: 1
    menu:
      top_nav:
        - name: European Hub
          url: https://www.covid19dataportal.org/
          weight: 20

  sv:
    languageName: Svenska
    contentDir: content/svenska
    weight: 2
    description: COVID-19 Dataportal för svensk forskning
    menu:
      top_nav:
        - name: Europeiska portalen
          url: https://www.covid19dataportal.org/
          weight: 20
